<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Court;

class CourtSeeder extends Seeder
{
    public function run(): void
    {
$courts = [
    // الملاعب الأساسية اللي عندك
    [
        'name'          => 'ملعب النصر',
        'sport_id'      => 1,
        'description'   => 'ملعب كرة قدم مجهز بالكامل',
        'address'       => 'مدينة نصر، القاهرة',
        'image'         => 'https://images.unsplash.com/photo-1529900748604-07564a03e7a6?w=400',
        'price_per_hour'=> 200,
        'latitude'      => 30.0444,
        'longitude'     => 31.2357,
        'rating'        => 4.5,
        'is_available'  => true,
    ],
    [
        'name'          => 'ملعب الأهلي',
        'sport_id'      => 1,
        'description'   => 'ملعب كرة قدم في قلب القاهرة',
        'address'       => 'وسط البلد، القاهرة',
        'image'         => 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=400',
        'price_per_hour'=> 250,
        'latitude'      => 30.0600,
        'longitude'     => 31.2200,
        'rating'        => 4.2,
        'is_available'  => true,
    ],
    [
        'name'          => 'ملعب بادل الرياضي',
        'sport_id'      => 2,
        'description'   => 'ملعب بادل احترافي',
        'address'       => 'المهندسين، الجيزة',
        'image'         => 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=400',
        'price_per_hour'=> 300,
        'latitude'      => 30.0500,
        'longitude'     => 31.2400,
        'rating'        => 4.8,
        'is_available'  => true,
    ],
    [
        'name'          => 'ملعب بادل النخبة',
        'sport_id'      => 2,
        'description'   => 'ملعب بادل مكيف',
        'address'       => 'الزمالك، القاهرة',
        'image'         => 'https://images.unsplash.com/photo-1599586120429-48281b6f0ece?w=400',
        'price_per_hour'=> 350,
        'latitude'      => 30.0550,
        'longitude'     => 31.2300,
        'rating'        => 4.6,
        'is_available'  => false,
    ],
    [
        'name'          => 'ملعب السلة الذهبي',
        'sport_id'      => 3,
        'description'   => 'ملعب كرة سلة بأرضية خشبية',
        'address'       => 'مصر الجديدة، القاهرة',
        'image'         => 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400',
        'price_per_hour'=> 150,
        'latitude'      => 30.0480,
        'longitude'     => 31.2450,
        'rating'        => 4.3,
        'is_available'  => true,
    ],
    [
        'name'          => 'ملعب السلة الأولمبي',
        'sport_id'      => 3,
        'description'   => 'ملعب كرة سلة في الهواء الطلق',
        'address'       => 'المعادي، القاهرة',
        'image'         => 'https://images.unsplash.com/photo-1504450758481-7338eba7524a?w=400',
        'price_per_hour'=> 180,
        'latitude'      => 30.0420,
        'longitude'     => 31.2500,
        'rating'        => 4.1,
        'is_available'  => true,
    ],

    // ==================== ملاعب كرة قدم جديدة (sport_id = 1) ====================
    [
        'name'          => 'ملعب الزمالك',
        'sport_id'      => 1,
        'description'   => 'ملعب كرة قدم نجيل طبيعي',
        'address'       => 'الزمالك، القاهرة',
        'image'         => 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=400',
        'price_per_hour'=> 300,
        'latitude'      => 30.0580,
        'longitude'     => 31.2250,
        'rating'        => 4.7,
        'is_available'  => true,
    ],
    [
        'name'          => 'ملعب اكتوبر',
        'sport_id'      => 1,
        'description'   => 'ملعب كرة قدم بمواصفات عالمية',
        'address'       => 'السادس من اكتوبر، الجيزة',
        'image'         => 'https://images.unsplash.com/photo-1459865264687-595d652de67e?w=400',
        'price_per_hour'=> 280,
        'latitude'      => 29.9800,
        'longitude'     => 30.9300,
        'rating'        => 4.4,
        'is_available'  => true,
    ],
    [
        'name'          => 'ملعب السلام',
        'sport_id'      => 1,
        'description'   => 'ملعب كرة قدم انارة ليلية',
        'address'       => 'السلام، القاهرة',
        'image'         => 'https://images.unsplash.com/photo-1517927033932-b3d18e61fb3a?w=400',
        'price_per_hour'=> 220,
        'latitude'      => 30.1500,
        'longitude'     => 31.3500,
        'rating'        => 4.0,
        'is_available'  => true,
    ],
    [
        'name'          => 'ملعب الرحاب',
        'sport_id'      => 1,
        'description'   => 'ملعب كرة قدم نجيل صناعي',
        'address'       => 'الرحاب، القاهرة',
        'image'         => 'https://images.unsplash.com/photo-1529900748604-07564a03e7a6?w=400',
        'price_per_hour'=> 260,
        'latitude'      => 30.0250,
        'longitude'     => 31.4800,
        'rating'        => 4.3,
        'is_available'  => true,
    ],
    [
        'name'          => 'ملعب مدينتي',
        'sport_id'      => 1,
        'description'   => 'ملعب كرة قدم فاخر',
        'address'       => 'مدينتي، القاهرة',
        'image'         => 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=400',
        'price_per_hour'=> 350,
        'latitude'      => 30.0320,
        'longitude'     => 31.4900,
        'rating'        => 4.8,
        'is_available'  => true,
    ],
    [
        'name'          => 'ملعب التجمع',
        'sport_id'      => 1,
        'description'   => 'ملعب كرة قدم في قلب التجمع',
        'address'       => 'التجمع الخامس، القاهرة',
        'image'         => 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=400',
        'price_per_hour'=> 320,
        'latitude'      => 30.0200,
        'longitude'     => 31.4400,
        'rating'        => 4.6,
        'is_available'  => true,
    ],
    [
        'name'          => 'ملعب العاصمة',
        'sport_id'      => 1,
        'description'   => 'ملعب كرة قدم أولمبي',
        'address'       => 'العاصمة الادارية، القاهرة',
        'image'         => 'https://images.unsplash.com/photo-1459865264687-595d652de67e?w=400',
        'price_per_hour'=> 400,
        'latitude'      => 30.0100,
        'longitude'     => 31.5000,
        'rating'        => 4.9,
        'is_available'  => true,
    ],
    [
        'name'          => 'ملعب الجيزة',
        'sport_id'      => 1,
        'description'   => 'ملعب كرة قدم في الجيزة',
        'address'       => 'الجيزة، الجيزة',
        'image'         => 'https://images.unsplash.com/photo-1517927033932-b3d18e61fb3a?w=400',
        'price_per_hour'=> 230,
        'latitude'      => 30.0130,
        'longitude'     => 31.2100,
        'rating'        => 4.1,
        'is_available'  => true,
    ],

    // ==================== ملاعب بادل جديدة (sport_id = 2) ====================
    [
        'name'          => 'بادل فيو',
        'sport_id'      => 2,
        'description'   => 'مدينة بادل متكاملة',
        'address'       => 'التجمع الخامس، القاهرة',
        'image'         => 'https://images.unsplash.com/photo-1622279455542-6a7c9d0cd6d1?w=400',
        'price_per_hour'=> 400,
        'latitude'      => 30.0200,
        'longitude'     => 31.4400,
        'rating'        => 4.9,
        'is_available'  => true,
    ],
    [
        'name'          => 'بادل كابيتال',
        'sport_id'      => 2,
        'description'   => 'ملعب بادل مغلق مكيف',
        'address'       => 'مدينة نصر، القاهرة',
        'image'         => 'https://images.unsplash.com/photo-1599586120429-48281b6f0ece?w=400',
        'price_per_hour'=> 380,
        'latitude'      => 30.0444,
        'longitude'     => 31.2500,
        'rating'        => 4.7,
        'is_available'  => true,
    ],
    [
        'name'          => 'بادل أكاديمي',
        'sport_id'      => 2,
        'description'   => 'أكاديمية بادل تدريب متقدم',
        'address'       => 'الشيخ زايد، الجيزة',
        'image'         => 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=400',
        'price_per_hour'=> 420,
        'latitude'      => 30.0100,
        'longitude'     => 31.2000,
        'rating'        => 4.8,
        'is_available'  => false,
    ],
    [
        'name'          => 'بادل بريميوم',
        'sport_id'      => 2,
        'description'   => 'ملعب بادل فاخر',
        'address'       => 'مدينتي، القاهرة',
        'image'         => 'https://images.unsplash.com/photo-1622279455542-6a7c9d0cd6d1?w=400',
        'price_per_hour'=> 450,
        'latitude'      => 30.0320,
        'longitude'     => 31.4900,
        'rating'        => 4.9,
        'is_available'  => true,
    ],
    [
        'name'          => 'بادل جاردنز',
        'sport_id'      => 2,
        'description'   => 'ملعب بادل في مدينة نصر',
        'address'       => 'مدينة نصر، القاهرة',
        'image'         => 'https://images.unsplash.com/photo-1599586120429-48281b6f0ece?w=400',
        'price_per_hour'=> 320,
        'latitude'      => 30.0480,
        'longitude'     => 31.2450,
        'rating'        => 4.5,
        'is_available'  => true,
    ],
    [
        'name'          => 'بادل كينج',
        'sport_id'      => 2,
        'description'   => 'ملعب بادل محترف',
        'address'       => 'السادس من اكتوبر، الجيزة',
        'image'         => 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=400',
        'price_per_hour'=> 360,
        'latitude'      => 29.9850,
        'longitude'     => 30.9400,
        'rating'        => 4.4,
        'is_available'  => true,
    ],
    [
        'name'          => 'بادل صن سيتي',
        'sport_id'      => 2,
        'description'   => 'ملعب بادل في الرحاب',
        'address'       => 'الرحاب، القاهرة',
        'image'         => 'https://images.unsplash.com/photo-1622279455542-6a7c9d0cd6d1?w=400',
        'price_per_hour'=> 340,
        'latitude'      => 30.0250,
        'longitude'     => 31.4800,
        'rating'        => 4.6,
        'is_available'  => true,
    ],

    // ==================== ملاعب كرة سلة جديدة (sport_id = 3) ====================
    [
        'name'          => 'سيتي جيم',
        'sport_id'      => 3,
        'description'   => 'صالة كرة سلة مغلقة',
        'address'       => 'العاصمة الادارية، القاهرة',
        'image'         => 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400',
        'price_per_hour'=> 200,
        'latitude'      => 30.0100,
        'longitude'     => 31.5000,
        'rating'        => 4.5,
        'is_available'  => true,
    ],
    [
        'name'          => 'هوبرز جيم',
        'sport_id'      => 3,
        'description'   => 'أرضية خشبية احترافية',
        'address'       => 'المهندسين، الجيزة',
        'image'         => 'https://images.unsplash.com/photo-1504450758481-7338eba7524a?w=400',
        'price_per_hour'=> 250,
        'latitude'      => 30.0550,
        'longitude'     => 31.2350,
        'rating'        => 4.6,
        'is_available'  => true,
    ],
    [
        'name'          => 'ستريت بول',
        'sport_id'      => 3,
        'description'   => 'ملعب كرة سلة شارع',
        'address'       => 'المقطم، القاهرة',
        'image'         => 'https://images.unsplash.com/photo-1558449028-b53a89d1c5b7?w=400',
        'price_per_hour'=> 100,
        'latitude'      => 30.0200,
        'longitude'     => 31.2800,
        'rating'        => 4.0,
        'is_available'  => true,
    ],
    [
        'name'          => 'فاميلي جيم',
        'sport_id'      => 3,
        'description'   => 'صالة متعددة الرياضات',
        'address'       => 'العاصمة الادارية، القاهرة',
        'image'         => 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400',
        'price_per_hour'=> 220,
        'latitude'      => 30.0120,
        'longitude'     => 31.5000,
        'rating'        => 4.4,
        'is_available'  => true,
    ],
    [
        'name'          => 'جولد كورنر',
        'sport_id'      => 3,
        'description'   => 'ملعب كرة سلة احترافي',
        'address'       => 'مدينتي، القاهرة',
        'image'         => 'https://images.unsplash.com/photo-1504450758481-7338eba7524a?w=400',
        'price_per_hour'=> 280,
        'latitude'      => 30.0320,
        'longitude'     => 31.4900,
        'rating'        => 4.7,
        'is_available'  => true,
    ],
    [
        'name'          => 'سلة الجزيرة',
        'sport_id'      => 3,
        'description'   => 'ملعب كرة سلة في الزمالك',
        'address'       => 'الزمالك، القاهرة',
        'image'         => 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400',
        'price_per_hour'=> 200,
        'latitude'      => 30.0600,
        'longitude'     => 31.2250,
        'rating'        => 4.3,
        'is_available'  => true,
    ],
    [
        'name'          => 'سلة مدينة نصر',
        'sport_id'      => 3,
        'description'   => 'ملعب كرة سلة في مدينة نصر',
        'address'       => 'مدينة نصر، القاهرة',
        'image'         => 'https://images.unsplash.com/photo-1558449028-b53a89d1c5b7?w=400',
        'price_per_hour'=> 170,
        'latitude'      => 30.0444,
        'longitude'     => 31.2357,
        'rating'        => 4.2,
        'is_available'  => true,
    ],
    [
        'name'          => 'سلة اكتوبر',
        'sport_id'      => 3,
        'description'   => 'ملعب كرة سلة في اكتوبر',
        'address'       => 'السادس من اكتوبر، الجيزة',
        'image'         => 'https://images.unsplash.com/photo-1504450758481-7338eba7524a?w=400',
        'price_per_hour'=> 190,
        'latitude'      => 29.9800,
        'longitude'     => 30.9300,
        'rating'        => 4.1,
        'is_available'  => true,
    ],
];

        foreach ($courts as $court) {
            Court::create($court);
        }
    }
}