// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Android configuration
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCARmehqVoC2rswUXdfxKNn9_Q09sEyAYE',
    appId: '1:924796587829:android:e40fd6720ac651a640867c',
    messagingSenderId: '924796587829',
    projectId: 'flutter-app-distribution-622c3',
    storageBucket: 'flutter-app-distribution-622c3.appspot.com',
  );

  // iOS configuration
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACmXj_QzYGh-KVtURM4-GaRD__jyvZz3Y',
    appId: '1:924796587829:ios:a27ee2cfe89a21fe40867c',
    messagingSenderId: '924796587829',
    projectId: 'flutter-app-distribution-622c3',
    storageBucket: 'flutter-app-distribution-622c3.appspot.com',
    iosBundleId: 'com.example.flutterCompleteProject',
  );

  // Web configuration
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyXXXXX-YOUR-WEB-API-KEY-XXXXX',
    appId: '1:924796587829:web:e40fd6720ac651a640867c',
    messagingSenderId: '924796587829',
    projectId: 'flutter-app-distribution-622c3',
    storageBucket: 'flutter-app-distribution-622c3.appspot.com',
  );
}
